namespace Hostel_Management_System.Forms
{
    partial class AddStudent
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddStudent));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel12 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel13 = new Bunifu.UI.WinForms.BunifuLabel();
            this.addgrdcontact = new Bunifu.UI.WinForms.BunifuTextBox();
            this.addgrdnic = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.addemail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            this.addbirthday = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.addgrdfname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.addgrdlaname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.addsex = new Bunifu.UI.WinForms.BunifuDropdown();
            this.addfname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.addlname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnaddStd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.addcontact = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.addaddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.addnic = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuFormDrag1 = new Bunifu.UI.WinForms.BunifuFormDrag();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuLabel12
            // 
            this.bunifuLabel12.AllowParentOverrides = false;
            this.bunifuLabel12.AutoEllipsis = false;
            this.bunifuLabel12.CursorType = null;
            this.bunifuLabel12.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel12.Location = new System.Drawing.Point(26, 123);
            this.bunifuLabel12.Name = "bunifuLabel12";
            this.bunifuLabel12.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel12.Size = new System.Drawing.Size(65, 21);
            this.bunifuLabel12.TabIndex = 22;
            this.bunifuLabel12.Text = "Contact :";
            this.bunifuLabel12.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel12.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel13
            // 
            this.bunifuLabel13.AllowParentOverrides = false;
            this.bunifuLabel13.AutoEllipsis = false;
            this.bunifuLabel13.CursorType = null;
            this.bunifuLabel13.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel13.Location = new System.Drawing.Point(55, 167);
            this.bunifuLabel13.Name = "bunifuLabel13";
            this.bunifuLabel13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel13.Size = new System.Drawing.Size(35, 21);
            this.bunifuLabel13.TabIndex = 23;
            this.bunifuLabel13.Text = "NIC :";
            this.bunifuLabel13.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel13.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // addgrdcontact
            // 
            this.addgrdcontact.AcceptsReturn = false;
            this.addgrdcontact.AcceptsTab = false;
            this.addgrdcontact.AnimationSpeed = 200;
            this.addgrdcontact.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addgrdcontact.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addgrdcontact.AutoSizeHeight = true;
            this.addgrdcontact.BackColor = System.Drawing.Color.Transparent;
            this.addgrdcontact.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addgrdcontact.BackgroundImage")));
            this.addgrdcontact.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addgrdcontact.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addgrdcontact.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addgrdcontact.BorderColorIdle = System.Drawing.Color.Silver;
            this.addgrdcontact.BorderRadius = 1;
            this.addgrdcontact.BorderThickness = 1;
            this.addgrdcontact.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.addgrdcontact.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addgrdcontact.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdcontact.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addgrdcontact.DefaultText = "";
            this.addgrdcontact.FillColor = System.Drawing.Color.White;
            this.addgrdcontact.HideSelection = true;
            this.addgrdcontact.IconLeft = null;
            this.addgrdcontact.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdcontact.IconPadding = 10;
            this.addgrdcontact.IconRight = null;
            this.addgrdcontact.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdcontact.Lines = new string[0];
            this.addgrdcontact.Location = new System.Drawing.Point(100, 116);
            this.addgrdcontact.MaxLength = 32767;
            this.addgrdcontact.MinimumSize = new System.Drawing.Size(1, 1);
            this.addgrdcontact.Modified = false;
            this.addgrdcontact.Multiline = false;
            this.addgrdcontact.Name = "addgrdcontact";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdcontact.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addgrdcontact.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdcontact.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdcontact.OnIdleState = stateProperties4;
            this.addgrdcontact.Padding = new System.Windows.Forms.Padding(3);
            this.addgrdcontact.PasswordChar = '\0';
            this.addgrdcontact.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addgrdcontact.PlaceholderText = "Enter text";
            this.addgrdcontact.ReadOnly = false;
            this.addgrdcontact.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addgrdcontact.SelectedText = "";
            this.addgrdcontact.SelectionLength = 0;
            this.addgrdcontact.SelectionStart = 0;
            this.addgrdcontact.ShortcutsEnabled = true;
            this.addgrdcontact.Size = new System.Drawing.Size(253, 39);
            this.addgrdcontact.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addgrdcontact.TabIndex = 24;
            this.addgrdcontact.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addgrdcontact.TextMarginBottom = 0;
            this.addgrdcontact.TextMarginLeft = 3;
            this.addgrdcontact.TextMarginTop = 1;
            this.addgrdcontact.TextPlaceholder = "Enter text";
            this.addgrdcontact.UseSystemPasswordChar = false;
            this.addgrdcontact.WordWrap = true;
            // 
            // addgrdnic
            // 
            this.addgrdnic.AcceptsReturn = false;
            this.addgrdnic.AcceptsTab = false;
            this.addgrdnic.AnimationSpeed = 200;
            this.addgrdnic.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addgrdnic.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addgrdnic.AutoSizeHeight = true;
            this.addgrdnic.BackColor = System.Drawing.Color.Transparent;
            this.addgrdnic.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addgrdnic.BackgroundImage")));
            this.addgrdnic.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addgrdnic.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addgrdnic.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addgrdnic.BorderColorIdle = System.Drawing.Color.Silver;
            this.addgrdnic.BorderRadius = 1;
            this.addgrdnic.BorderThickness = 1;
            this.addgrdnic.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.addgrdnic.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addgrdnic.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdnic.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addgrdnic.DefaultText = "";
            this.addgrdnic.FillColor = System.Drawing.Color.White;
            this.addgrdnic.HideSelection = true;
            this.addgrdnic.IconLeft = null;
            this.addgrdnic.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdnic.IconPadding = 10;
            this.addgrdnic.IconRight = null;
            this.addgrdnic.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdnic.Lines = new string[0];
            this.addgrdnic.Location = new System.Drawing.Point(100, 158);
            this.addgrdnic.MaxLength = 32767;
            this.addgrdnic.MinimumSize = new System.Drawing.Size(1, 1);
            this.addgrdnic.Modified = false;
            this.addgrdnic.Multiline = false;
            this.addgrdnic.Name = "addgrdnic";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdnic.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addgrdnic.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdnic.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdnic.OnIdleState = stateProperties8;
            this.addgrdnic.Padding = new System.Windows.Forms.Padding(3);
            this.addgrdnic.PasswordChar = '\0';
            this.addgrdnic.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addgrdnic.PlaceholderText = "Enter text";
            this.addgrdnic.ReadOnly = false;
            this.addgrdnic.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addgrdnic.SelectedText = "";
            this.addgrdnic.SelectionLength = 0;
            this.addgrdnic.SelectionStart = 0;
            this.addgrdnic.ShortcutsEnabled = true;
            this.addgrdnic.Size = new System.Drawing.Size(253, 39);
            this.addgrdnic.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addgrdnic.TabIndex = 25;
            this.addgrdnic.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addgrdnic.TextMarginBottom = 0;
            this.addgrdnic.TextMarginLeft = 3;
            this.addgrdnic.TextMarginTop = 1;
            this.addgrdnic.TextPlaceholder = "Enter text";
            this.addgrdnic.UseSystemPasswordChar = false;
            this.addgrdnic.WordWrap = true;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel10.Location = new System.Drawing.Point(9, 76);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(84, 21);
            this.bunifuLabel10.TabIndex = 19;
            this.bunifuLabel10.Text = "Last Name :";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // addemail
            // 
            this.addemail.AcceptsReturn = false;
            this.addemail.AcceptsTab = false;
            this.addemail.AnimationSpeed = 200;
            this.addemail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addemail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addemail.AutoSizeHeight = true;
            this.addemail.BackColor = System.Drawing.Color.Transparent;
            this.addemail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addemail.BackgroundImage")));
            this.addemail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addemail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addemail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addemail.BorderColorIdle = System.Drawing.Color.Silver;
            this.addemail.BorderRadius = 1;
            this.addemail.BorderThickness = 1;
            this.addemail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.addemail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addemail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addemail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addemail.DefaultText = "";
            this.addemail.FillColor = System.Drawing.Color.White;
            this.addemail.HideSelection = true;
            this.addemail.IconLeft = null;
            this.addemail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addemail.IconPadding = 10;
            this.addemail.IconRight = null;
            this.addemail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addemail.Lines = new string[0];
            this.addemail.Location = new System.Drawing.Point(98, 317);
            this.addemail.MaxLength = 32767;
            this.addemail.MinimumSize = new System.Drawing.Size(1, 1);
            this.addemail.Modified = false;
            this.addemail.Multiline = false;
            this.addemail.Name = "addemail";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addemail.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addemail.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addemail.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addemail.OnIdleState = stateProperties12;
            this.addemail.Padding = new System.Windows.Forms.Padding(3);
            this.addemail.PasswordChar = '\0';
            this.addemail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addemail.PlaceholderText = "Enter text";
            this.addemail.ReadOnly = false;
            this.addemail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addemail.SelectedText = "";
            this.addemail.SelectionLength = 0;
            this.addemail.SelectionStart = 0;
            this.addemail.ShortcutsEnabled = true;
            this.addemail.Size = new System.Drawing.Size(253, 39);
            this.addemail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addemail.TabIndex = 17;
            this.addemail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addemail.TextMarginBottom = 0;
            this.addemail.TextMarginLeft = 3;
            this.addemail.TextMarginTop = 1;
            this.addemail.TextPlaceholder = "Enter text";
            this.addemail.UseSystemPasswordChar = false;
            this.addemail.WordWrap = true;
            // 
            // bunifuLabel11
            // 
            this.bunifuLabel11.AllowParentOverrides = false;
            this.bunifuLabel11.AutoEllipsis = false;
            this.bunifuLabel11.CursorType = null;
            this.bunifuLabel11.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel11.Location = new System.Drawing.Point(9, 34);
            this.bunifuLabel11.Name = "bunifuLabel11";
            this.bunifuLabel11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel11.Size = new System.Drawing.Size(86, 21);
            this.bunifuLabel11.TabIndex = 18;
            this.bunifuLabel11.Text = "First Name :";
            this.bunifuLabel11.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // addbirthday
            // 
            this.addbirthday.BackColor = System.Drawing.Color.Transparent;
            this.addbirthday.BorderColor = System.Drawing.Color.Silver;
            this.addbirthday.BorderRadius = 1;
            this.addbirthday.Color = System.Drawing.Color.Silver;
            this.addbirthday.CustomFormat = "dd-MM-yyyy";
            this.addbirthday.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.addbirthday.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.addbirthday.DisabledColor = System.Drawing.Color.Gray;
            this.addbirthday.DisplayWeekNumbers = false;
            this.addbirthday.DPHeight = 0;
            this.addbirthday.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.addbirthday.FillDatePicker = false;
            this.addbirthday.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.addbirthday.ForeColor = System.Drawing.Color.Black;
            this.addbirthday.Icon = ((System.Drawing.Image)(resources.GetObject("addbirthday.Icon")));
            this.addbirthday.IconColor = System.Drawing.Color.Gray;
            this.addbirthday.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.addbirthday.LeftTextMargin = 5;
            this.addbirthday.Location = new System.Drawing.Point(98, 200);
            this.addbirthday.MinimumSize = new System.Drawing.Size(4, 32);
            this.addbirthday.Name = "addbirthday";
            this.addbirthday.Size = new System.Drawing.Size(253, 32);
            this.addbirthday.TabIndex = 22;
            this.addbirthday.Value = new System.DateTime(2023, 4, 13, 20, 50, 0, 0);
            // 
            // addgrdfname
            // 
            this.addgrdfname.AcceptsReturn = false;
            this.addgrdfname.AcceptsTab = false;
            this.addgrdfname.AnimationSpeed = 200;
            this.addgrdfname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addgrdfname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addgrdfname.AutoSizeHeight = true;
            this.addgrdfname.BackColor = System.Drawing.Color.Transparent;
            this.addgrdfname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addgrdfname.BackgroundImage")));
            this.addgrdfname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addgrdfname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addgrdfname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addgrdfname.BorderColorIdle = System.Drawing.Color.Silver;
            this.addgrdfname.BorderRadius = 1;
            this.addgrdfname.BorderThickness = 1;
            this.addgrdfname.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.addgrdfname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addgrdfname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdfname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addgrdfname.DefaultText = "";
            this.addgrdfname.FillColor = System.Drawing.Color.White;
            this.addgrdfname.HideSelection = true;
            this.addgrdfname.IconLeft = null;
            this.addgrdfname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdfname.IconPadding = 10;
            this.addgrdfname.IconRight = null;
            this.addgrdfname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdfname.Lines = new string[0];
            this.addgrdfname.Location = new System.Drawing.Point(100, 29);
            this.addgrdfname.MaxLength = 32767;
            this.addgrdfname.MinimumSize = new System.Drawing.Size(1, 1);
            this.addgrdfname.Modified = false;
            this.addgrdfname.Multiline = false;
            this.addgrdfname.Name = "addgrdfname";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdfname.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addgrdfname.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdfname.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdfname.OnIdleState = stateProperties16;
            this.addgrdfname.Padding = new System.Windows.Forms.Padding(3);
            this.addgrdfname.PasswordChar = '\0';
            this.addgrdfname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addgrdfname.PlaceholderText = "Enter text";
            this.addgrdfname.ReadOnly = false;
            this.addgrdfname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addgrdfname.SelectedText = "";
            this.addgrdfname.SelectionLength = 0;
            this.addgrdfname.SelectionStart = 0;
            this.addgrdfname.ShortcutsEnabled = true;
            this.addgrdfname.Size = new System.Drawing.Size(253, 39);
            this.addgrdfname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addgrdfname.TabIndex = 20;
            this.addgrdfname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addgrdfname.TextMarginBottom = 0;
            this.addgrdfname.TextMarginLeft = 3;
            this.addgrdfname.TextMarginTop = 1;
            this.addgrdfname.TextPlaceholder = "Enter text";
            this.addgrdfname.UseSystemPasswordChar = false;
            this.addgrdfname.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel5.Location = new System.Drawing.Point(22, 123);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(68, 21);
            this.bunifuLabel5.TabIndex = 6;
            this.bunifuLabel5.Text = "Address :";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // addgrdlaname
            // 
            this.addgrdlaname.AcceptsReturn = false;
            this.addgrdlaname.AcceptsTab = false;
            this.addgrdlaname.AnimationSpeed = 200;
            this.addgrdlaname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addgrdlaname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addgrdlaname.AutoSizeHeight = true;
            this.addgrdlaname.BackColor = System.Drawing.Color.Transparent;
            this.addgrdlaname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addgrdlaname.BackgroundImage")));
            this.addgrdlaname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addgrdlaname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addgrdlaname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addgrdlaname.BorderColorIdle = System.Drawing.Color.Silver;
            this.addgrdlaname.BorderRadius = 1;
            this.addgrdlaname.BorderThickness = 1;
            this.addgrdlaname.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.addgrdlaname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addgrdlaname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdlaname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addgrdlaname.DefaultText = "";
            this.addgrdlaname.FillColor = System.Drawing.Color.White;
            this.addgrdlaname.HideSelection = true;
            this.addgrdlaname.IconLeft = null;
            this.addgrdlaname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdlaname.IconPadding = 10;
            this.addgrdlaname.IconRight = null;
            this.addgrdlaname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addgrdlaname.Lines = new string[0];
            this.addgrdlaname.Location = new System.Drawing.Point(100, 71);
            this.addgrdlaname.MaxLength = 32767;
            this.addgrdlaname.MinimumSize = new System.Drawing.Size(1, 1);
            this.addgrdlaname.Modified = false;
            this.addgrdlaname.Multiline = false;
            this.addgrdlaname.Name = "addgrdlaname";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdlaname.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addgrdlaname.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdlaname.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addgrdlaname.OnIdleState = stateProperties20;
            this.addgrdlaname.Padding = new System.Windows.Forms.Padding(3);
            this.addgrdlaname.PasswordChar = '\0';
            this.addgrdlaname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addgrdlaname.PlaceholderText = "Enter text";
            this.addgrdlaname.ReadOnly = false;
            this.addgrdlaname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addgrdlaname.SelectedText = "";
            this.addgrdlaname.SelectionLength = 0;
            this.addgrdlaname.SelectionStart = 0;
            this.addgrdlaname.ShortcutsEnabled = true;
            this.addgrdlaname.Size = new System.Drawing.Size(253, 39);
            this.addgrdlaname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addgrdlaname.TabIndex = 21;
            this.addgrdlaname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addgrdlaname.TextMarginBottom = 0;
            this.addgrdlaname.TextMarginLeft = 3;
            this.addgrdlaname.TextMarginTop = 1;
            this.addgrdlaname.TextPlaceholder = "Enter text";
            this.addgrdlaname.UseSystemPasswordChar = false;
            this.addgrdlaname.WordWrap = true;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel12);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel13);
            this.bunifuGroupBox1.Controls.Add(this.addgrdcontact);
            this.bunifuGroupBox1.Controls.Add(this.addgrdnic);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel11);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel10);
            this.bunifuGroupBox1.Controls.Add(this.addgrdfname);
            this.bunifuGroupBox1.Controls.Add(this.addgrdlaname);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(50, 445);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(364, 219);
            this.bunifuGroupBox1.TabIndex = 29;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Guardian Details";
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(10, 32);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(86, 21);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "First Name :";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.Location = new System.Drawing.Point(10, 75);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(84, 21);
            this.bunifuLabel3.TabIndex = 3;
            this.bunifuLabel3.Text = "Last Name :";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // addsex
            // 
            this.addsex.BackColor = System.Drawing.Color.Transparent;
            this.addsex.BackgroundColor = System.Drawing.Color.White;
            this.addsex.BorderColor = System.Drawing.Color.Silver;
            this.addsex.BorderRadius = 1;
            this.addsex.Color = System.Drawing.Color.Silver;
            this.addsex.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.addsex.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.addsex.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addsex.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.addsex.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.addsex.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.addsex.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.addsex.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.addsex.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.addsex.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.addsex.FillDropDown = true;
            this.addsex.FillIndicator = false;
            this.addsex.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.addsex.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.addsex.ForeColor = System.Drawing.Color.Black;
            this.addsex.FormattingEnabled = true;
            this.addsex.Icon = null;
            this.addsex.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.addsex.IndicatorColor = System.Drawing.Color.DarkGray;
            this.addsex.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.addsex.IndicatorThickness = 2;
            this.addsex.IsDropdownOpened = false;
            this.addsex.ItemBackColor = System.Drawing.Color.White;
            this.addsex.ItemBorderColor = System.Drawing.Color.White;
            this.addsex.ItemForeColor = System.Drawing.Color.Black;
            this.addsex.ItemHeight = 26;
            this.addsex.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.addsex.ItemHighLightForeColor = System.Drawing.Color.White;
            this.addsex.Items.AddRange(new object[] {
            "Male",
            "Female",
            "Other"});
            this.addsex.ItemTopMargin = 3;
            this.addsex.Location = new System.Drawing.Point(97, 238);
            this.addsex.Name = "addsex";
            this.addsex.Size = new System.Drawing.Size(254, 32);
            this.addsex.TabIndex = 23;
            this.addsex.Text = null;
            this.addsex.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.addsex.TextLeftMargin = 5;
            // 
            // addfname
            // 
            this.addfname.AcceptsReturn = false;
            this.addfname.AcceptsTab = false;
            this.addfname.AnimationSpeed = 200;
            this.addfname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addfname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addfname.AutoSizeHeight = true;
            this.addfname.BackColor = System.Drawing.Color.Transparent;
            this.addfname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addfname.BackgroundImage")));
            this.addfname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addfname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addfname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addfname.BorderColorIdle = System.Drawing.Color.Silver;
            this.addfname.BorderRadius = 1;
            this.addfname.BorderThickness = 1;
            this.addfname.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.addfname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addfname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addfname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addfname.DefaultText = "";
            this.addfname.FillColor = System.Drawing.Color.White;
            this.addfname.HideSelection = true;
            this.addfname.IconLeft = null;
            this.addfname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addfname.IconPadding = 10;
            this.addfname.IconRight = null;
            this.addfname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addfname.Lines = new string[0];
            this.addfname.Location = new System.Drawing.Point(98, 25);
            this.addfname.MaxLength = 32767;
            this.addfname.MinimumSize = new System.Drawing.Size(1, 1);
            this.addfname.Modified = false;
            this.addfname.Multiline = false;
            this.addfname.Name = "addfname";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addfname.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addfname.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addfname.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addfname.OnIdleState = stateProperties24;
            this.addfname.Padding = new System.Windows.Forms.Padding(3);
            this.addfname.PasswordChar = '\0';
            this.addfname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addfname.PlaceholderText = "Enter text";
            this.addfname.ReadOnly = false;
            this.addfname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addfname.SelectedText = "";
            this.addfname.SelectionLength = 0;
            this.addfname.SelectionStart = 0;
            this.addfname.ShortcutsEnabled = true;
            this.addfname.Size = new System.Drawing.Size(253, 39);
            this.addfname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addfname.TabIndex = 4;
            this.addfname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addfname.TextMarginBottom = 0;
            this.addfname.TextMarginLeft = 3;
            this.addfname.TextMarginTop = 1;
            this.addfname.TextPlaceholder = "Enter text";
            this.addfname.UseSystemPasswordChar = false;
            this.addfname.WordWrap = true;
            // 
            // addlname
            // 
            this.addlname.AcceptsReturn = false;
            this.addlname.AcceptsTab = false;
            this.addlname.AnimationSpeed = 200;
            this.addlname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addlname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addlname.AutoSizeHeight = true;
            this.addlname.BackColor = System.Drawing.Color.Transparent;
            this.addlname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addlname.BackgroundImage")));
            this.addlname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addlname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addlname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addlname.BorderColorIdle = System.Drawing.Color.Silver;
            this.addlname.BorderRadius = 1;
            this.addlname.BorderThickness = 1;
            this.addlname.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.addlname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addlname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addlname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addlname.DefaultText = "";
            this.addlname.FillColor = System.Drawing.Color.White;
            this.addlname.HideSelection = true;
            this.addlname.IconLeft = null;
            this.addlname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addlname.IconPadding = 10;
            this.addlname.IconRight = null;
            this.addlname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addlname.Lines = new string[0];
            this.addlname.Location = new System.Drawing.Point(98, 70);
            this.addlname.MaxLength = 32767;
            this.addlname.MinimumSize = new System.Drawing.Size(1, 1);
            this.addlname.Modified = false;
            this.addlname.Multiline = false;
            this.addlname.Name = "addlname";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addlname.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addlname.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addlname.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addlname.OnIdleState = stateProperties28;
            this.addlname.Padding = new System.Windows.Forms.Padding(3);
            this.addlname.PasswordChar = '\0';
            this.addlname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addlname.PlaceholderText = "Enter text";
            this.addlname.ReadOnly = false;
            this.addlname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addlname.SelectedText = "";
            this.addlname.SelectionLength = 0;
            this.addlname.SelectionStart = 0;
            this.addlname.ShortcutsEnabled = true;
            this.addlname.Size = new System.Drawing.Size(253, 39);
            this.addlname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addlname.TabIndex = 5;
            this.addlname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addlname.TextMarginBottom = 0;
            this.addlname.TextMarginLeft = 3;
            this.addlname.TextMarginTop = 1;
            this.addlname.TextPlaceholder = "Enter text";
            this.addlname.UseSystemPasswordChar = false;
            this.addlname.WordWrap = true;
            // 
            // btnaddStd
            // 
            this.btnaddStd.AllowAnimations = true;
            this.btnaddStd.AllowMouseEffects = true;
            this.btnaddStd.AllowToggling = false;
            this.btnaddStd.AnimationSpeed = 200;
            this.btnaddStd.AutoGenerateColors = false;
            this.btnaddStd.AutoRoundBorders = false;
            this.btnaddStd.AutoSizeLeftIcon = true;
            this.btnaddStd.AutoSizeRightIcon = true;
            this.btnaddStd.BackColor = System.Drawing.Color.Transparent;
            this.btnaddStd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnaddStd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnaddStd.BackgroundImage")));
            this.btnaddStd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnaddStd.ButtonText = "Add";
            this.btnaddStd.ButtonTextMarginLeft = 0;
            this.btnaddStd.ColorContrastOnClick = 45;
            this.btnaddStd.ColorContrastOnHover = 45;
            this.btnaddStd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnaddStd.CustomizableEdges = borderEdges1;
            this.btnaddStd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnaddStd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnaddStd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnaddStd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnaddStd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnaddStd.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnaddStd.ForeColor = System.Drawing.Color.White;
            this.btnaddStd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnaddStd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnaddStd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnaddStd.IconMarginLeft = 11;
            this.btnaddStd.IconPadding = 10;
            this.btnaddStd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnaddStd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnaddStd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnaddStd.IconSize = 25;
            this.btnaddStd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnaddStd.IdleBorderRadius = 5;
            this.btnaddStd.IdleBorderThickness = 1;
            this.btnaddStd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnaddStd.IdleIconLeftImage = null;
            this.btnaddStd.IdleIconRightImage = null;
            this.btnaddStd.IndicateFocus = false;
            this.btnaddStd.Location = new System.Drawing.Point(150, 685);
            this.btnaddStd.Name = "btnaddStd";
            this.btnaddStd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnaddStd.OnDisabledState.BorderRadius = 5;
            this.btnaddStd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnaddStd.OnDisabledState.BorderThickness = 1;
            this.btnaddStd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnaddStd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnaddStd.OnDisabledState.IconLeftImage = null;
            this.btnaddStd.OnDisabledState.IconRightImage = null;
            this.btnaddStd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnaddStd.onHoverState.BorderRadius = 5;
            this.btnaddStd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnaddStd.onHoverState.BorderThickness = 1;
            this.btnaddStd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnaddStd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnaddStd.onHoverState.IconLeftImage = null;
            this.btnaddStd.onHoverState.IconRightImage = null;
            this.btnaddStd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnaddStd.OnIdleState.BorderRadius = 5;
            this.btnaddStd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnaddStd.OnIdleState.BorderThickness = 1;
            this.btnaddStd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnaddStd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnaddStd.OnIdleState.IconLeftImage = null;
            this.btnaddStd.OnIdleState.IconRightImage = null;
            this.btnaddStd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnaddStd.OnPressedState.BorderRadius = 5;
            this.btnaddStd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnaddStd.OnPressedState.BorderThickness = 1;
            this.btnaddStd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnaddStd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnaddStd.OnPressedState.IconLeftImage = null;
            this.btnaddStd.OnPressedState.IconRightImage = null;
            this.btnaddStd.Size = new System.Drawing.Size(150, 39);
            this.btnaddStd.TabIndex = 31;
            this.btnaddStd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnaddStd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnaddStd.TextMarginLeft = 0;
            this.btnaddStd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnaddStd.UseDefaultRadiusAndThickness = true;
            this.btnaddStd.Click += new System.EventHandler(this.btnaddStd_Click);
            // 
            // addcontact
            // 
            this.addcontact.AcceptsReturn = false;
            this.addcontact.AcceptsTab = false;
            this.addcontact.AnimationSpeed = 200;
            this.addcontact.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addcontact.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addcontact.AutoSizeHeight = true;
            this.addcontact.BackColor = System.Drawing.Color.Transparent;
            this.addcontact.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addcontact.BackgroundImage")));
            this.addcontact.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addcontact.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addcontact.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addcontact.BorderColorIdle = System.Drawing.Color.Silver;
            this.addcontact.BorderRadius = 1;
            this.addcontact.BorderThickness = 1;
            this.addcontact.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.addcontact.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addcontact.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addcontact.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addcontact.DefaultText = "";
            this.addcontact.FillColor = System.Drawing.Color.White;
            this.addcontact.HideSelection = true;
            this.addcontact.IconLeft = null;
            this.addcontact.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addcontact.IconPadding = 10;
            this.addcontact.IconRight = null;
            this.addcontact.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addcontact.Lines = new string[0];
            this.addcontact.Location = new System.Drawing.Point(98, 276);
            this.addcontact.MaxLength = 32767;
            this.addcontact.MinimumSize = new System.Drawing.Size(1, 1);
            this.addcontact.Modified = false;
            this.addcontact.Multiline = false;
            this.addcontact.Name = "addcontact";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addcontact.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addcontact.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addcontact.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addcontact.OnIdleState = stateProperties32;
            this.addcontact.Padding = new System.Windows.Forms.Padding(3);
            this.addcontact.PasswordChar = '\0';
            this.addcontact.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addcontact.PlaceholderText = "Enter text";
            this.addcontact.ReadOnly = false;
            this.addcontact.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addcontact.SelectedText = "";
            this.addcontact.SelectionLength = 0;
            this.addcontact.SelectionStart = 0;
            this.addcontact.ShortcutsEnabled = true;
            this.addcontact.Size = new System.Drawing.Size(253, 39);
            this.addcontact.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addcontact.TabIndex = 16;
            this.addcontact.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addcontact.TextMarginBottom = 0;
            this.addcontact.TextMarginLeft = 3;
            this.addcontact.TextMarginTop = 1;
            this.addcontact.TextPlaceholder = "Enter text";
            this.addcontact.UseSystemPasswordChar = false;
            this.addcontact.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel8.Location = new System.Drawing.Point(41, 325);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(46, 21);
            this.bunifuLabel8.TabIndex = 15;
            this.bunifuLabel8.Text = "Email :";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel2);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel3);
            this.bunifuGroupBox2.Controls.Add(this.addsex);
            this.bunifuGroupBox2.Controls.Add(this.addfname);
            this.bunifuGroupBox2.Controls.Add(this.addbirthday);
            this.bunifuGroupBox2.Controls.Add(this.addlname);
            this.bunifuGroupBox2.Controls.Add(this.addemail);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel5);
            this.bunifuGroupBox2.Controls.Add(this.addcontact);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel4);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel8);
            this.bunifuGroupBox2.Controls.Add(this.addaddress);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel9);
            this.bunifuGroupBox2.Controls.Add(this.addnic);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel7);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel6);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(50, 68);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(364, 371);
            this.bunifuGroupBox2.TabIndex = 30;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Student Details";
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.Location = new System.Drawing.Point(55, 169);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(35, 21);
            this.bunifuLabel4.TabIndex = 7;
            this.bunifuLabel4.Text = "NIC :";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // addaddress
            // 
            this.addaddress.AcceptsReturn = false;
            this.addaddress.AcceptsTab = false;
            this.addaddress.AnimationSpeed = 200;
            this.addaddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addaddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addaddress.AutoSizeHeight = true;
            this.addaddress.BackColor = System.Drawing.Color.Transparent;
            this.addaddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addaddress.BackgroundImage")));
            this.addaddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addaddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addaddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addaddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.addaddress.BorderRadius = 1;
            this.addaddress.BorderThickness = 1;
            this.addaddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.addaddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addaddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addaddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addaddress.DefaultText = "";
            this.addaddress.FillColor = System.Drawing.Color.White;
            this.addaddress.HideSelection = true;
            this.addaddress.IconLeft = null;
            this.addaddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addaddress.IconPadding = 10;
            this.addaddress.IconRight = null;
            this.addaddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addaddress.Lines = new string[0];
            this.addaddress.Location = new System.Drawing.Point(98, 115);
            this.addaddress.MaxLength = 32767;
            this.addaddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.addaddress.Modified = false;
            this.addaddress.Multiline = false;
            this.addaddress.Name = "addaddress";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addaddress.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addaddress.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addaddress.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addaddress.OnIdleState = stateProperties36;
            this.addaddress.Padding = new System.Windows.Forms.Padding(3);
            this.addaddress.PasswordChar = '\0';
            this.addaddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addaddress.PlaceholderText = "Enter text";
            this.addaddress.ReadOnly = false;
            this.addaddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addaddress.SelectedText = "";
            this.addaddress.SelectionLength = 0;
            this.addaddress.SelectionStart = 0;
            this.addaddress.ShortcutsEnabled = true;
            this.addaddress.Size = new System.Drawing.Size(253, 39);
            this.addaddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addaddress.TabIndex = 8;
            this.addaddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addaddress.TextMarginBottom = 0;
            this.addaddress.TextMarginLeft = 3;
            this.addaddress.TextMarginTop = 1;
            this.addaddress.TextPlaceholder = "Enter text";
            this.addaddress.UseSystemPasswordChar = false;
            this.addaddress.WordWrap = true;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel9.Location = new System.Drawing.Point(22, 284);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(65, 21);
            this.bunifuLabel9.TabIndex = 14;
            this.bunifuLabel9.Text = "Contact :";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // addnic
            // 
            this.addnic.AcceptsReturn = false;
            this.addnic.AcceptsTab = false;
            this.addnic.AnimationSpeed = 200;
            this.addnic.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addnic.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addnic.AutoSizeHeight = true;
            this.addnic.BackColor = System.Drawing.Color.Transparent;
            this.addnic.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addnic.BackgroundImage")));
            this.addnic.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addnic.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addnic.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addnic.BorderColorIdle = System.Drawing.Color.Silver;
            this.addnic.BorderRadius = 1;
            this.addnic.BorderThickness = 1;
            this.addnic.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.addnic.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addnic.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addnic.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addnic.DefaultText = "";
            this.addnic.FillColor = System.Drawing.Color.White;
            this.addnic.HideSelection = true;
            this.addnic.IconLeft = null;
            this.addnic.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addnic.IconPadding = 10;
            this.addnic.IconRight = null;
            this.addnic.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addnic.Lines = new string[0];
            this.addnic.Location = new System.Drawing.Point(98, 160);
            this.addnic.MaxLength = 32767;
            this.addnic.MinimumSize = new System.Drawing.Size(1, 1);
            this.addnic.Modified = false;
            this.addnic.Multiline = false;
            this.addnic.Name = "addnic";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addnic.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addnic.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addnic.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addnic.OnIdleState = stateProperties40;
            this.addnic.Padding = new System.Windows.Forms.Padding(3);
            this.addnic.PasswordChar = '\0';
            this.addnic.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addnic.PlaceholderText = "Enter text";
            this.addnic.ReadOnly = false;
            this.addnic.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addnic.SelectedText = "";
            this.addnic.SelectionLength = 0;
            this.addnic.SelectionStart = 0;
            this.addnic.ShortcutsEnabled = true;
            this.addnic.Size = new System.Drawing.Size(253, 39);
            this.addnic.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addnic.TabIndex = 9;
            this.addnic.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addnic.TextMarginBottom = 0;
            this.addnic.TextMarginLeft = 3;
            this.addnic.TextMarginTop = 1;
            this.addnic.TextPlaceholder = "Enter text";
            this.addnic.UseSystemPasswordChar = false;
            this.addnic.WordWrap = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel7.Location = new System.Drawing.Point(20, 205);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(69, 21);
            this.bunifuLabel7.TabIndex = 10;
            this.bunifuLabel7.Text = "Birthday :";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel6.Location = new System.Drawing.Point(52, 241);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(34, 21);
            this.bunifuLabel6.TabIndex = 11;
            this.bunifuLabel6.Text = "Sex :";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(405, 11);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = false;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(44, 41);
            this.bunifuFormControlBox1.TabIndex = 28;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(175, 17);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(125, 30);
            this.bunifuLabel1.TabIndex = 27;
            this.bunifuLabel1.Text = "Add Student";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuFormDrag1
            // 
            this.bunifuFormDrag1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDrag1.ContainerControl = this;
            this.bunifuFormDrag1.DockIndicatorsOpacity = 0.5D;
            this.bunifuFormDrag1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDrag1.DockingOptions.DockAll = true;
            this.bunifuFormDrag1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDrag1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDrag1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDrag1.DockingOptions.DockLeft = true;
            this.bunifuFormDrag1.DockingOptions.DockRight = true;
            this.bunifuFormDrag1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDrag1.DockingOptions.DockTopRight = true;
            this.bunifuFormDrag1.DragOpacity = 0.9D;
            this.bunifuFormDrag1.Enabled = true;
            this.bunifuFormDrag1.ParentForm = this;
            this.bunifuFormDrag1.ShowCursorChanges = true;
            this.bunifuFormDrag1.ShowDockingIndicators = true;
            this.bunifuFormDrag1.TitleBarOptions.BunifuFormDrag = this.bunifuFormDrag1;
            this.bunifuFormDrag1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDrag1.TitleBarOptions.Enabled = true;
            this.bunifuFormDrag1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDrag1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 5;
            this.bunifuElipse1.TargetControl = this;
            // 
            // AddStudent
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(460, 752);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.btnaddStd);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuFormControlBox1);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AddStudent";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "AddStudent";
            this.Load += new System.EventHandler(this.AddStudent_Load);
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuGroupBox2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel12;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel13;
        private Bunifu.UI.WinForms.BunifuTextBox addgrdcontact;
        private Bunifu.UI.WinForms.BunifuTextBox addgrdnic;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuTextBox addemail;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuDatePicker addbirthday;
        private Bunifu.UI.WinForms.BunifuTextBox addgrdfname;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox addgrdlaname;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuDropdown addsex;
        private Bunifu.UI.WinForms.BunifuTextBox addfname;
        private Bunifu.UI.WinForms.BunifuTextBox addlname;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnaddStd;
        private Bunifu.UI.WinForms.BunifuTextBox addcontact;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox addaddress;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox addnic;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuFormDrag bunifuFormDrag1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
    }
}